name: weathertech
version: 1.0.0+1
publish_to: 'none'

description: WeatherTech IoT Dashboard Mobile Application

environment:
  sdk: '^3.10.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  
  # Charts and Data Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.2.3
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Network and Images
  cached_network_image: ^3.3.0
  
  # Utility
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300